version: 2

sources:
  - name: statsbomb_data
    description: "Les données brutes de Statsbomb."
    tables:
      - name: raw_competitions
        description: "Table des competitions brute."
      - name: raw_lineups
        description: "Table des compositions des matchs brute"
      - name: raw_matches
        description: "Table des matches brute par saison"
      - name: raw_events
        description: "Table de tous les evenements présent dans chaque matchs"
